import type { NextPage } from 'next';
import Head from 'next/head';
import ClaimYourNFTs from '../src/components/ClaimYourNFTs';
import BannerSection from '../src/components/BannerSection';
import WelcomeSection from '../src/components/WelcomeSection';
import MintYourCharacter from '../src/components/MintYourCharacter';
import CTASection from '../src/components/CTASection';

import WelcomeBG from '../src/assets/images/welcome-bg.jpg';
import NftLogo from '../src/assets/images/nft-logo.png';

const Home: NextPage = () => {
  console.log(WelcomeBG);
  return (
    <div className="mint-page">
      <Head>
        <title>Meta Cars | Mint</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BannerSection />

      <div className="welcome-section relative z-30 -mt-24 flex items-center justify-center overflow-hidden">
        <div className="welcome-inner z-20 w-full pb-[10rem]">
          <div className="w-full max-w-siteContainer mx-auto px-8">
            <div className="nft-logo mb-14">
              <img
                className="w-full max-w-[32.8rem] m-auto"
                src={NftLogo.src}
                alt="nft-logo"
              />
            </div>
            <div className="divider-1 w-[90%] md:w-full max-w-[71rem] m-auto h-[.2rem] bg-[#3AACFF] mb-8"></div>
            <div className="divider-2 w-full max-w-[106rem] m-auto h-[.2rem] bg-[#3AACFF] mb-8"></div>

            <WelcomeSection />

            <div className="divider-1 w-[90%] md:w-full max-w-[71rem] m-auto h-[.2rem] bg-[#3AACFF] mb-8"></div>
            <div className="divider-2 w-full max-w-[106rem] m-auto h-[.2rem] bg-[#3AACFF] mb-8"></div>

            <MintYourCharacter />
            <CTASection />
            <div className="divider-1 w-[90%] md:w-full max-w-[71rem] m-auto h-[.2rem] bg-[#3AACFF] mb-8"></div>
            <div className="divider-2 w-full max-w-[106rem] m-auto h-[.2rem] bg-[#3AACFF] mb-8"></div>
          </div>
        </div>
        <img
          className="absolute w-full h-full object-cover object-top"
          src={WelcomeBG.src}
          alt="banner-bg"
        />
      </div>

      <ClaimYourNFTs />
    </div>
  );
};

export default Home;
